language: python
python:
#  - "3.4"
#  - "3.5"
  - "3.6"
#  - "3.7-dev"
install:
  - pip install -r requirements.txt
script:
#  - 'pushd docs; make html; popd'
  - 'sh tests/physical_exam.sh'

branches:
  only:
    - master
    # test checkはdevelopへのmerge
    - develop
