language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
virtualenv:
  system_site_packages: true
install:
  - pip install -r requirements.txt
script:
  - 'pushd docs; make html; popd'
  - 'sh tests/physical_exam.sh'

branches:
  only:
    - master
